import "./globals.css";
import Header from "@/components/header/Header";
import Container from "@mui/material/Container";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Container maxWidth="xl" sx={{ pt: 1 }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
